<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="vajra" duration-ms="18010" started-at="2021-03-22T18:37:00 IST" finished-at="2021-03-22T18:37:18 IST">
    <groups>
    </groups>
    <test name="Vajra" duration-ms="18010" started-at="2021-03-22T18:37:00 IST" finished-at="2021-03-22T18:37:18 IST">
      <class name="com.vajra.TestClass.TC_AllLogin_001">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.vajra.TestClass.TC_AllLogin_001@2833cc44]" name="setup" is-config="true" duration-ms="3820" started-at="2021-03-22T18:37:00 IST" finished-at="2021-03-22T18:37:03 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="Login_TestCase_SE()[pri:0, instance:com.vajra.TestClass.TC_AllLogin_001@2833cc44]" name="Login_TestCase_SE" duration-ms="3325" started-at="2021-03-22T18:37:03 IST" finished-at="2021-03-22T18:37:07 IST">
          <exception class="junit.framework.ComparisonFailure">
            <message>
              <![CDATA[expected:<Login> but was:<Sales - Dashboard - Sales>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.ComparisonFailure: expected:<Login> but was:<Sales - Dashboard - Sales>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at com.vajra.TestClass.TC_AllLogin_001.Login_TestCase_SE(TC_AllLogin_001.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.ComparisonFailure -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_TestCase_SE -->
        <test-method status="PASS" signature="Login_TestCase_OrderSection()[pri:1, instance:com.vajra.TestClass.TC_AllLogin_001@2833cc44]" name="Login_TestCase_OrderSection" duration-ms="4720" started-at="2021-03-22T18:37:07 IST" finished-at="2021-03-22T18:37:11 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_TestCase_OrderSection -->
        <test-method status="PASS" signature="Login_TestCase_Cashier()[pri:2, instance:com.vajra.TestClass.TC_AllLogin_001@2833cc44]" name="Login_TestCase_Cashier" duration-ms="1680" started-at="2021-03-22T18:37:11 IST" finished-at="2021-03-22T18:37:13 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_TestCase_Cashier -->
        <test-method status="PASS" signature="Login_TestCase_StoreHead()[pri:3, instance:com.vajra.TestClass.TC_AllLogin_001@2833cc44]" name="Login_TestCase_StoreHead" duration-ms="1220" started-at="2021-03-22T18:37:13 IST" finished-at="2021-03-22T18:37:14 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_TestCase_StoreHead -->
        <test-method status="PASS" signature="Login_TestCase_OE()[pri:4, instance:com.vajra.TestClass.TC_AllLogin_001@2833cc44]" name="Login_TestCase_OE" duration-ms="3184" started-at="2021-03-22T18:37:14 IST" finished-at="2021-03-22T18:37:18 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_TestCase_OE -->
      </class> <!-- com.vajra.TestClass.TC_AllLogin_001 -->
    </test> <!-- Vajra -->
  </suite> <!-- vajra -->
</testng-results>
